---

spring:
#  r2dbc:
#    url: r2dbc:h2:mem:///mydb
#    username: sa
#    password: password
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG